#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-readme_renderer
Version  : 33.0
Release  : 26
URL      : https://files.pythonhosted.org/packages/17/dc/df354d98bf99652bfda3e6458389b35d6ae76243363cd54efc6579fff32c/readme_renderer-33.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/17/dc/df354d98bf99652bfda3e6458389b35d6ae76243363cd54efc6579fff32c/readme_renderer-33.0.tar.gz
Summary  : readme_renderer is a library for rendering "readme" descriptions for Warehouse
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-readme_renderer-license = %{version}-%{release}
Requires: pypi-readme_renderer-python = %{version}-%{release}
Requires: pypi-readme_renderer-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(bleach)
BuildRequires : pypi(docutils)
BuildRequires : pypi(py)
BuildRequires : pypi(pygments)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
Readme Renderer
===============
Readme Renderer is a library that will safely render arbitrary
render the ``long_description`` for packages. It can handle Markdown,
reStructuredText (``.rst``), and plain text.

%package license
Summary: license components for the pypi-readme_renderer package.
Group: Default

%description license
license components for the pypi-readme_renderer package.


%package python
Summary: python components for the pypi-readme_renderer package.
Group: Default
Requires: pypi-readme_renderer-python3 = %{version}-%{release}

%description python
python components for the pypi-readme_renderer package.


%package python3
Summary: python3 components for the pypi-readme_renderer package.
Group: Default
Requires: python3-core
Provides: pypi(readme_renderer)
Requires: pypi(bleach)
Requires: pypi(docutils)
Requires: pypi(pygments)

%description python3
python3 components for the pypi-readme_renderer package.


%prep
%setup -q -n readme_renderer-33.0
cd %{_builddir}/readme_renderer-33.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646511418
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-readme_renderer
cp %{_builddir}/readme_renderer-33.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-readme_renderer/43a3a49bd7af636c923a5ae475395b8e29320529
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-readme_renderer/43a3a49bd7af636c923a5ae475395b8e29320529

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
